# Generated by Django 3.0.6 on 2020-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'кандидата', 'verbose_name_plural': 'кандидат'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
    ]
