# Generated by Django 3.0.6 on 2020-05-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20200517_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество голосов'),
        ),
    ]
