# Generated by Django 3.0.6 on 2020-05-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_candidate_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='biography',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(max_length=200, null=True, verbose_name='Фамилия'),
        ),
    ]
