# Generated by Django 3.0.6 on 2020-05-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_candidate_election_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank='True', null='True', upload_to='static\\images')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.Image'),
        ),
    ]
