# Generated by Django 3.0.6 on 2020-05-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20200518_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank='True', null='True', upload_to='static\\images', verbose_name='Изображение'),
        ),
    ]
