# Generated by Django 3.0.6 on 2020-05-17 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20200518_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.Image', verbose_name='Изображение'),
        ),
    ]
