# Generated by Django 3.0.6 on 2020-05-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20200518_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='fair/static', verbose_name='Изображение'),
        ),
    ]
