# Generated by Django 3.0.6 on 2020-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20200518_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение'),
        ),
    ]
