# Generated by Django 3.0.6 on 2020-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20200518_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images', verbose_name='Изображение'),
        ),
    ]
