# Generated by Django 3.0.6 on 2020-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_auto_20200518_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество голосов'),
        ),
    ]
