# Generated by Django 3.0.6 on 2020-05-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0022_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_candidates', to='voting.Candidate', verbose_name='Кандидат'),
        ),
    ]
